# Generated by Django 3.1.2 on 2020-10-06 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
